### ISSUE TITLE
Speeding up drag/drop

### ISSUE THREAD

**Issue by rwwagner90** [kaliber5/ember-drag-sort#32]
Is there any way to make the drag/drop faster and more seamless? Right now, it feels like nothing is happening sometimes while the logic in the background happens, then the item shows back up like a half second later.

**Comment by lolmaus** [comment]
Hey @rwwagner90, do you mean logic within the addon or logic implemented in your app?

**Comment by lolmaus** [comment]
Also, does "nothing is happening" refer to dragging or dropping?

**Comment by rwwagner90** [comment]
@lolmaus I mean speeding up the dropping behavior of the addon. It is reproducible in the demos of the addon. If you drag and drop, after you drop, it takes awhile for the element to be inserted in, so it appears nothing is happening, then it all the sudden shows up.

**Comment by lolmaus** [comment]
For me the behavior of demos is instantaneous, both on my PC and my old (but still rather fast) laptop.

On my Android phone I *think* I can notice a delay, but it's very small, like 100ms and certainly not noticeable unless you make effort to look for it.

Is there anything specific you do in the demo apart from normal drag-n-drop to reproduce the issue?

***

Given the design of this addon, I cannot think of a way to solve this problem.

The addon relies on the following sequence:

1. You release the mouse button to drop.
2. An action is called.
3. The action modifies the content of the arrays (either directly or by triggering CP recomputation).
4. Ember rerenders the lists according to how they updated.

The addon does have use the index of the `each` helper when you provide it.

If one of the steps in this cycle is slow, I don't think the addon can do anything to speed up things.

Other addons/libs are using different techniques. For example, jQuery Sortable would first move the dragged DOM node into the new position and only then call the action. This certainly feels more snappy, but is not declarative.

***

That said, I'm open to suggestions. If you have any specific idea in mind, please share.

**Comment by rwwagner90** [comment]
@lolmaus I just tried on another laptop and you are right, it is instantaneous. There is something about my new 16" MacBook Pro that must be different than a year old 15". I am going to try to get a gif.

**Comment by rwwagner90** [comment]
It seems that when I drop the item on the 16" the preview animates down. You can see it sliding and fading away, and then once it disappears the item appears in the list again. On the 15", it does not happen. There is no animation and it appears immediately.

![Kapture 2019-12-02 at 9 32 44](https://user-images.githubusercontent.com/2640861/69967805-2b9e0a80-14e7-11ea-8b45-db4fece23243.gif)

**Comment by lolmaus** [comment]
Is that in Safari?

**Comment by rwwagner90** [comment]
@lolmaus no, in Chrome. Both are on latest Chrome. On 15" MacBook there is no animation, on 16" there is the animation causing the perception of slowness.

**Comment by lolmaus** [comment]
I have no idea what is causing this. 😔 

Maybe an `event.preventDefault()` somewhere could prevent the animation. Wanna try it out?

**Comment by rwwagner90** [comment]
@lolmaus where would I put that?

**Comment by lolmaus** [comment]
@rwwagner90 The events are handled in the `drag-sort-list` and `drag-sort-item` components, [like this](https://github.com/kaliber5/ember-drag-sort/blob/gen-1/addon/components/drag-sort-item.js#L149).

There are also a couple PRs open which might either fix your issue or give a clue how to handle it. Please check them out!

**Comment by rwwagner90** [comment]
@lolmaus https://github.com/kaliber5/ember-drag-sort/pull/30 also seems to fix this issue. Any chance we could get it in?

**Comment by lolmaus** [comment]
@rwwagner90 I'll merge and release them together with your PR. Is that OK?

**Comment by rwwagner90** [comment]
@lolmaus I would go ahead and merge the other PRs, since they are not related to mine. That would close out this issue and fix https://github.com/kaliber5/ember-drag-sort/issues/16 officially.

If you want to wait and cut a release after mine is in that is fine, but I wouldn't wait to merge.

**Comment by lolmaus** [comment]
@rwwagner90 Merged. Please see if `2.0.0-beta.1` resolves this issue.

**Comment by rwwagner90** [comment]
It should resolve this issue 👍
