### ISSUE TITLE
Feature - vanilla js version

### ISSUE THREAD

**Issue by yairEO** [kaliber5/ember-drag-sort#41]
Hi, I am an author of another open-source project, [Tagify](https://github.com/yairEO/tagify/), and I am on the hunt for a good drag&drop script to use in my project. Looking for a script which is tiny (less than 30k unminified), well-written, and does the job well. 

Yours seems great but unfortunately it is only for Ember. 
Any plans on vanilla version?

Thanks!

**Comment by lolmaus** [comment]
Hey, @yairEO!

Thank you for your interest in the addon.

Unfortunately, it is heavily integrated with Ember, and extracting the logic into a standalone version is not feasible.

There should be other libraries, though. Before migrating to Ember, I've been using jQuery Sortable, which is very robust. I'm sure lightweight equivalents are also available.

**Comment by yairEO** [comment]
Thanks, just found this one, which is not exactly smooth but does the job with minimum code: https://github.com/lukasoppermann/html5sortable

I also started [writing my own](https://codepen.io/vsync/pen/xmxqgP) (1.7kb minified) but have decided to let it go since I was based on HTML5 drag & drop and eventually saw it was really crappy and not smooth at all as plain JS can achieve
