### ISSUE TITLE
Support for horizontal lists

### ISSUE THREAD

**Issue by lolmaus** [kaliber5/ember-drag-sort#6]
Current implementation compares current and previous **vertical** mouse pointer position to drag direction.

It would be nice to allow user choose between vertical and horizontal direction.

**Comment by wwallace** [comment]
@lolmaus I am currently working on this. I expect to be able to submit a PR today or tomorrow at the latest. I am adding an argument called `horizontalSort : true`, which defaults to `undefined` per the existing default argument values.

**Comment by lolmaus** [comment]
Nice! 

> which defaults to `undefined`

We have a practice of displaying available params like this:

```js
Component.extend({
  horizontalSort: null,
})
```

**Comment by frysch** [comment]
Any news regarding this one? @wwallace @lolmaus

**Comment by lolmaus** [comment]
@frysch I'm not actively working on this feature.

Wanna make a PR?

**Comment by frysch** [comment]
I might do that. Just thought there might be one on the way from wwallace after reading his comment. But i guess, since it's almost a year ago, there might have come something in between 😀

**Comment by lolmaus** [comment]
Implemented in #26 by @frysch. Kudos!

Released as `2.0.0-beta.0`.
